services:
  server:
    image: server
    pull_policy: never
    container_name: server
    build:
      context: server
      dockerfile: ./Dockerfile
      target: ${NODE_ENV}  
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "5555:5555" # this is the port for prisma studio
    command: ["npm", "run", "migrate:populate:start_dev"] # uncomment only when running for the first time (to populate the database)
    volumes: # for development 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
        restart: true


  db:
    image: postgres:15.10-alpine
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata: 
  pgadmin-data:
